server:
  port: 8080

spring:
  application:
    name: ite-3rd-ecommerce

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ite_ecommerce_db
    username: postgres
    password: qwer

  jpa:
    hibernate:
      ddl-auto: update